language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: '5.6'
          env:
            - COMPOSER_FLAGS="--prefer-lowest"
            - COVERAGE=true
        - php: '5.6'
          env: LARAVEL_VERSION=5.1.*
        - php: '5.6'
          env: LARAVEL_VERSION=5.2.*
        - php: '7.0'
          env: COVERAGE=true

before_install:
    - set -e;
    - if [ -n "COVERAGE" ]; then
        wget https://scrutinizer-ci.com/ocular.phar;
      else
        phpenv config-rm xdebug.ini;
      fi;
    - if [ -n "$LARAVEL_VERSION" ]; then
        composer require "laravel/framework:${LARAVEL_VERSION}" --no-update;
      fi;
    - rm -rf tests/Functional/cache/*

install:
    - composer update --prefer-dist $COMPOSER_FLAGS

script:
    - bin/phpunit -c phpunit.xml.dist --coverage-text

after_script:
    - if [ -n "COVERAGE" ]; then
        php ocular.phar code-coverage:upload --format=php-clover coverage.xml;
      fi;

notifications:
    email: false
